CREATE TABLE Movies (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
service_id INT,
name VARCHAR(255),
description VARCHAR(510),
genre VARCHAR(255),
year CHAR(4),
cast VARCHAR(510),
director VARCHAR(255),
url VARCHAR(255)
);


CREATE TABLE Services (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255),
avatar VARCHAR(255)
);

CREATE TABLE Comments (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
movie_id INT,
comment VARCHAR(510),
name VARCHAR(255),
account VARCHAR(255),
date DATETIME
);

CREATE TABLE Likes (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
movie_id INT,
email VARCHAR(255)
);

CREATE TABLE Feeds (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
movie_id INT,
date DATETIME,
FOREIGN KEY(movie_id) REFERENCES Movies (id)
);

ALTER TABLE Movies ADD FOREIGN KEY(service_id) REFERENCES Services (id);
ALTER TABLE Comments ADD FOREIGN KEY(movie_id) REFERENCES Feeds (id);
ALTER TABLE Likes ADD FOREIGN KEY(movie_id) REFERENCES Feeds (id);
